### ISSUE TITLE
Error Loading Workflow from File

### ISSUE THREAD

**Issue by cjgordon** [materialsproject/fireworks#115] opened 2015-07-29 04:09 UTC
Hi,

First of, great library!

There is only one thing I would like to do which I cannot get to work and that is load a workflow from a file and execute it as part of a python script.

For example I would like to do something like:

    from fireworks import Firework, LaunchPad, ScriptTask
    from fireworks.core.rocket_launcher import launch_rocket

    # set up the LaunchPad and reset it
    launchpad = LaunchPad()
    launchpad.reset('', require_password=False)

    fw = Firework.from_file("/home/chris/dev/fireworks/fw_tutorials/org_wf.yaml")

    # store workflow and launch it locally
    launchpad.add_wf(fw)
    launch_rocket(launchpad)    

However I get the following error:
    Traceback (most recent call last):
      File "WorkflowEngine.py", line 12, in <module>
        fw = Firework.from_file("/levaux/tests/fireworkstest/org_wf.yaml")
      File "/usr/local/lib/python2.7/dist-packages/fireworks/utilities/fw_serializers.py", line 253, in from_file
        return cls.from_format(f.read(), f_format=f_format)
      File "/usr/local/lib/python2.7/dist-packages/fireworks/utilities/fw_serializers.py", line 228, in from_format
        yaml.load(f_str, Loader=Loader)))
      File "/usr/local/lib/python2.7/dist-packages/fireworks/utilities/fw_serializers.py", line 145, in _decorator
        m_dict = func(self, *new_args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/fireworks/core/firework.py", line 311, in from_dict
    tasks = m_dict['spec']['_tasks']
    KeyError: u'spec'

I can however load and execute simpler single fireworks like: fw_test.yaml

Thanks in advance.

Cheers
Chris

**Comment by computron** [comment] 2015-07-29 21:28
Hi Chris,

For future requests, you can use:
https://groups.google.com/forum/#!forum/fireworkflows

I don't have a problem loading workflows like org_wf.yaml when I try it. The error message refers to a "WorkflowEngine", which is not part of FireWorks. Is this something you've added?

If you are confident the issue is with FireWorks and not with something custom that you've added, you can also try attaching the workflow file that you are trying to add, then I can try to reproduce your problem better.

**Comment by cjgordon** [comment] 2015-07-30 01:05
WorkflowEngine.py is just the name of the file name I'm using for the code block in original post. Just wanted to check it was an intended feature to load whole workflows. I will investigate more and report back in a day or so. 

Thanks for swift response.

**Comment by computron** [comment] 2015-07-30 01:14
Hi,

Yes you should definitely be able to load whole workflows. e.g. this
tutorial has a few examples of that:

https://pythonhosted.org/FireWorks/workflow_tutorial.html

Actually, even when you load a single FireWork, it is being converted into
a Workflow under the hood.

Best,
Anubhav

**Comment by computron** [comment] 2015-08-14 16:27
Hi,

I have not heard from you in a bit so I am closing this issue. Please feel free to re-open if you feel there is still a problem.

**Closed by computron** 2015-08-14 16:27 UTC
