### ISSUE TITLE
Calling `lpad webgui` opens two identical tabs

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#93] opened 2015-04-30 17:51 UTC
As the title says, running `lpad webgui` seems to open the same page in two different tabs or windows.

**Comment by computron** [comment] 2015-05-04 15:50
Hi,

I can't reproduce this problem on a Mac OS/X Yosemite; calling "lpad webgui" opens up only a single tab. Would you be able to provide some details of your environment?

Note that it's unlikely I will be able to debug this issue since I can't reproduce, and nothing in the code looks obviously off. If you have a solution I'm happy to merge it; one workaround (other than closing the added tab) is to run the command in server mode ("lpad webgui -s") and open up the browser yourself.

**Comment by jakirkham** [comment] 2015-05-04 15:52
Alright, let me look into this further. Any pointers as to place to look?

**Comment by computron** [comment] 2015-05-04 15:55
Ok, the browser opening is in: fireworks/scripts/lpad_run.py:411

```
def webgui(args):
    os.environ["FWDB_CONFIG"] = json.dumps(get_lp(args).to_dict())
    from fireworks.flask_site.app import app
    from multiprocessing import Process
    p1 = Process(target=app.run, kwargs={"host": args.host, "port": args.port})
    p1.start()
    if not args.server_mode:
        import webbrowser
        time.sleep(2)
        webbrowser.open("http://{}:{}".format(args.host, args.port))
    p1.join()
```

**Comment by jakirkham** [comment] 2015-05-04 15:58
Perfect, thanks. I will take a look.

**Comment by computron** [comment] 2015-05-11 03:34
I am closing this issue for now - please re-open if needed

**Closed by computron** 2015-05-11 03:34 UTC

**Comment by jakirkham** [comment] 2015-05-13 14:26
Yeah, it appears I am not allowed to reopen issues on your issue tracker. Regardless, this appears to be a bug in the browser I am using.

**Comment by jakirkham** [comment] 2015-05-13 14:30
Actually, I disagree with that assessment now. I tried a variety of browsers only Safari did not have this problem. This is still a bug.

**Comment by jakirkham** [comment] 2015-05-13 14:34
@computron please try using Firefox or Chrome and let me know if you still are not able to reproduce this.

**Comment by gpetretto** [comment] 2015-05-13 15:03
Hi,
I could reproduce the problem on my laptop (linux+chrome/ff). 
Replacing the line
    p1 = Process(target=app.run, kwargs={"host": args.host, "port": args.port})
with 
    p1 = Process(target=app.run, kwargs={"host": args.host, "port": args.port, "debug": False})
in the webgui function seems to fix the problem. Can you check if this is the case for you as well? 
Thanks

**Comment by jakirkham** [comment] 2015-05-13 15:09
Hi @gpetretto, I tried your fix and this appears to work with Firefox, Chrome, and Safari. Though Safari never had the problem previously, I think its worth noting that it doesn't seem to have hurt it. Thanks for taking a look.
